/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[Sample]
(
[PersonID] [int] NULL,
[LastName] [varchar] (255) NULL,
[FirstName] [varchar] (255) NULL,
[Address] [varchar] (255) NULL,
[City] [varchar] (255) NULL
)
GO
