/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ZL\L04R6835861')
CREATE LOGIN [ZL\L04R6835861] FROM WINDOWS
GO
CREATE USER [ZL\L04R6835861] FOR LOGIN [ZL\L04R6835861]
GO
